### ISSUE TITLE
Aninews doesn't return the full description

### ISSUE THREAD

**Issue by sagniksen31** [DriftAsimov/animec#10]
Aninews doesn't return the full description, it is mainly incomplete. Happens the same with Anilyrics.
somewhat like this

Here is a collection of promotional videos (PV), television ads (CM), and trailers for the last week. This thread excludes videos that have already been featured in an article. Please check the News Board, under the Preview tag, for articles that feature a promotional video. Last week's PV thread can be found here. Aggressive Retsuko (ONA) 4th Season | ONA | Trailer The trailer for the fourth season of Aggressive Retsuko reveals that the anime is set to premiere worldwide through the streaming s...

Thank You

**Comment by Tanishquasar** [comment]
Can you please describe steps to reproduce this issue or simply the code you used

**Comment by sagniksen31** [comment]
`from animec import *
result = Aninews()
print(result.titles)
print(result.description)`

**Comment by sagniksen31** [comment]
from animec import *
result = Aninews()
print(result.titles)
print(result.description)

**Comment by sagniksen31** [comment]
used the code above, was thinking to make ad discord bot that returns anime news charachters etc.
But the Aninews descriptions are not always full, and sometimes this happens with anilyrics

**Comment by Tanishquasar** [comment]
In the case of `Aninews` it's because MyAnimeList returns only the summary with `Ellipsis (...)` at the end.
So might be the case with `AniLyrics`
